# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'musicKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for musicKit
  pod 'Alamofire'


  target 'musicKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'musicKitUITests' do
    # Pods for testing
  end

end
